import json
from pathlib import Path

metrics_path = Path("artifacts/release/metrics/results.json")

if not metrics_path.exists():
    raise FileNotFoundError("results.json was not generated by the packet sniffer")

with open(metrics_path, "r") as f:
    data = json.load(f)

required_fields = [
    "total_packets",
    "syn_packets",
    "ack_packets",
    "non_syn_packets",
    "alerts",
    "bpf_filter",
    "syn_threshold",
    "detection_type",
]

missing = [field for field in required_fields if field not in data]

if missing:
    raise ValueError(f"Missing metrics fields: {missing}")

print("Metrics validation passed")
print(json.dumps(data, indent=2))